"""
C-Array Exporter — generates .h header files with PROGMEM bitmap arrays.

Supports formats: horizontal, vertical, page.
Reports total memory usage in the header comment.
"""

import os
from ..canvas import Canvas


def export_c_array(
    frames: list,
    output_path: str,
    width: int,
    height: int,
    fps: int,
    fmt: str = "horizontal",
    var_prefix: str = "frame",
):
    """Export rendered frames as a C header file with PROGMEM arrays.

    Args:
        frames: list of Canvas objects
        output_path: path to write the .h file
        width: screen width
        height: screen height
        fps: animation FPS
        fmt: byte format ("horizontal", "vertical", "page")
        var_prefix: prefix for frame variable names
    """
    frame_count = len(frames)
    frame_size = (width * height) // 8
    total_bytes = frame_count * frame_size
    total_kb = total_bytes / 1024.0

    format_labels = {
        "horizontal": "Row-major (Adafruit_GFX / SSD1306)",
        "vertical": "Column-major (ST7565 / SH1106)",
        "page": "Page-based (U8g2 / U8x8)",
    }

    lines = []
    lines.append(f"// ============================================================")
    lines.append(f"// Auto-generated by remotionBinario")
    lines.append(f"// Screen: {width}x{height} | Frames: {frame_count} | FPS: {fps}")
    lines.append(f"// Format: {format_labels.get(fmt, fmt)}")
    lines.append(f"// Frame size: {frame_size} bytes | Total: {total_kb:.2f} KB ({total_bytes} bytes)")
    lines.append(f"// ============================================================")
    lines.append("")
    lines.append("#include <avr/pgmspace.h>")
    lines.append("")

    bytes_per_row = width // 8 if fmt == "horizontal" else 16

    for i, canvas in enumerate(frames):
        data = canvas.to_bytes(fmt)
        lines.append(f"const unsigned char PROGMEM {var_prefix}_{i}[] = {{")

        hex_values = [f"0x{b:02X}" for b in data]

        for row_start in range(0, len(hex_values), bytes_per_row):
            row = hex_values[row_start : row_start + bytes_per_row]
            comma = "," if row_start + bytes_per_row < len(hex_values) else ""
            lines.append(f"  {', '.join(row)}{comma}")

        lines.append("};")
        lines.append("")

    lines.append(f"const unsigned char* const {var_prefix}s[] PROGMEM = {{")
    frame_refs = [f"  {var_prefix}_{i}" for i in range(frame_count)]
    lines.append(",\n".join(frame_refs))
    lines.append("};")
    lines.append("")

    lines.append(f"const uint16_t FRAME_COUNT = {frame_count};")
    lines.append(f"const uint16_t FRAME_W = {width};")
    lines.append(f"const uint16_t FRAME_H = {height};")
    lines.append(f"const uint8_t  FPS = {fps};")
    lines.append(f"const uint16_t FRAME_SIZE = {frame_size};")
    lines.append("")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return {
        "path": output_path,
        "frame_count": frame_count,
        "frame_size": frame_size,
        "total_bytes": total_bytes,
        "total_kb": total_kb,
    }
